name: Git Checks

on: [pull_request]

jobs:
  block-wip-pr:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@2.0.0
    - name: Block WIP PR
      uses: samholmes/block-wip-pr-action@1.2.0

